### PR TITLE
allow comments to specify that they need to be scrolled to

### PR DESCRIPTION
**Pull request by deoxxa**

### CODE REVIEW

**Comment by deoxxa** [comment]
Please review this before merging!

**Comment by nelix** [comment]
Seems like an odd thing to have as a bool...
How about just making it a function the parent can call when it wants to scroll it into view. Its a little more flexible.

**Comment by deoxxa** [comment]
The problem I faced is that there seems to be no way to get to the `Comment` instance if you're just rendering a comment thread. There's this weird inversion of control thing going on that means the only way to influence the `Comment` instances from outside the `Comments` component is to pass different data into them.

**Comment by nelix** [comment]
I'm sure you know that this is a sign of wrong abstraction... But I'd consider merging this until we have time to totally refactor the way comments handle data... The API is all wrong wrong wrong.

I can't think of a better solution to this in the short term....

**Comment by deoxxa** [comment]
Well... Is this used at all in Stack? Or is it just Brief?

**Comment by nelix** [comment]
Just Brief, mostly due to me not liking the API.
Shall I merge this? Then we can sit down and make a new API that meets the needs of stack and Brief?

**Comment by grapegravity** [comment]
Just chucking in my 2¢, the API on this is a mess and I have been wanting to refactor it for ages.

**Pull request merged**
