### PR TITLE
almost total replacing of the todo component

### PR DESCRIPTION
**Pull request by nelix**
Depends on #185 and #184 

Attempts to make the component more consistent with other parts of the UI, with save/cancel handling on items and the create input.

### CODE REVIEW

**Comment by grapegravity** [comment]
Using “Escape” to cancel editing doesn’t work because this listens on `keydown` and the dialog listens on `keyup`. Worth integrating `key-mixin` into the alert to mitigate this?

**Comment by nelix** [comment]
Oh yes, I'd love too. I'll do that now.

**Comment by nelix** [comment]
That said those are bugs inside cancellable-edit/alert/modal. Any comments for this branch?

**Comment by grapegravity** [comment]
Which block this from passing muster, so it might be a good move to make this work?

**Comment by nelix** [comment]
But, the existing cancellable is broken and that has nothing to do with this?

**Comment by nelix** [comment]
I guess no point having two broken components?

**Pull request merged**
