### PR TITLE
Adds a hover state function for inline :hover

### PR DESCRIPTION
**Pull request by ojame**
have your :cake: and :fork_and_knife: it too.

### CODE REVIEW

**Comment by grapegravity** [comment]
One thing that comes to mind here is that coupling the state to a hardcoded key means we can’t support hover states for multiple elements within a component. That _might_ become an issue.

**Comment by ojame** [comment]
I kinda think the abstraction should save it, each component itself is responsible for managing its own hover, not the parent.

That said, components that have a bunch of html that requires hover states could prove to be an issue. What are your suggestions?

**Comment by grapegravity** [comment]
I mean it may well, you’re right. If everything hoverable is its own thing. [Radium takes the same approach (but with support for more events)](https://github.com/FormidableLabs/radium/blob/d2d354180b0111bce2a842caade8c2d9e2246f59/modules/mixins/browser-state.js#L13-L19).

**Comment by ojame** [comment]
Yep, we leaned a lot on the way Readium implements it's handler :+1:

**Pull request merged**
