### PR TITLE
Add ability to define a maxLength on cancelable-edit

### PR DESCRIPTION
**Pull request by nelix**

### CODE REVIEW

**Comment by grapegravity** [comment]
I appreciate that this is a thing you want to get out fast, but I feel like just not responding to keyboard input after you reach the length is less than ideal. Would disabling submission and showing a message below the input work?

screen shot 2015-03-04 at 10 39 25 am

**Comment by jessta** [comment]
What happens if I paste something longer than the max length?

**Comment by nelix** [comment]
The issue with options besides truncation, is that then the user must delete things in order to be able to submit. My 99% case for the input having more than 10kb of data in it is that someone has had a clipboard accident rather than actually typing 10kb into the description box.

**Comment by nelix** [comment]
@jessta it pastes n chars, and the rest are truncated

**Comment by nelix** [comment]
I'd be happy to put up an issue to add a nice visual validation system, and to accept external validators.
But I also need to fix a unrecoverable error that is happening in production in the mean time.

**Comment by nelix** [comment]
@grapegravity I think the use case for a more advanced validation system (outside of this component ideally, so we can use it on our registration form, and in this component too) is strong. 
@ojame posted this today: http://codepen.io/mikepro4/pen/pvKYZG

**Comment by grapegravity** [comment]
Okay I’m happy to pull back on this but I'll also point out that we can defer to browser behaviour in HTML5 compliant browsers; https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-maxlength

**Comment by grapegravity** [comment]
By which I mean, given that’s how `maxlength` works on a native `<textarea/>`.

**Comment by nelix** [comment]
I'll take a look at how HTML5 deals with this, and consider my options. Thanks @grapegravity

**Comment by nelix** [comment]
Looks like maxLength also works on Input type="text" too. I'll revise this.

**Comment by grapegravity** [comment]
:guitar: :notes:

**Comment by nelix** [comment]
:hamster: :dancers:

**Pull request merged**
