### PR TITLE
Remove old app header

### PR DESCRIPTION
**Pull request by ojame**
Stack doesn't use these anymore (brief might... but we don't care). I realised i was converting this useless junk to post-css.

### CODE REVIEW

**Comment by grapegravity** [comment]
:crying_cat_face:

**Comment by alandownie** [comment]
brief is dead

**Comment by alandownie** [comment]
sorry

**Comment by grapegravity** [comment]
long live brief

**Comment by nelix** [comment]
/me pours out half of his 40 ounce

**Comment by alandownie** [comment]
asif

**Comment by jessta** [comment]
:( brief was with us so...briefly
capture

**Pull request merged**
