### PR TITLE
Transpile js to avoid shipping ES6 to registry

### PR DESCRIPTION
**Pull request by aussiegeek**

### CODE REVIEW

**Comment by ticky** [comment]
Hmm, compiling the files into the same directory feels like a bad idea, honestly. Feels ripe for filename autocomplete confusion.

**Comment by aussiegeek** [comment]
The .jsx files aren't being shipped. Open to concrete suggestions on what to do instead

**Comment by ticky** [comment]
Well yes but .js files will ostensibly at least sometimes end up sitting in the filesystem next to their uncompiled counterparts

**Comment by nelix** [comment]
looks good to me @aussiegeek :+1: can't wait to not have to babel things in node_modules :D

**Pull request merged**
